version: '3.8'

services:
  bot:
    build: .
    container_name: trading-bot
    volumes:
      - .:/app
    command: python src/main.py
    depends_on:
      - dashboard

  dashboard:
    build: .
    container_name: trading-dashboard
    command: python dashboard/app.py
    ports:
      - "8050:8050"
